/**
 * Aspose.Imaging Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/FilterPropertiesBase'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./FilterPropertiesBase'));
  } else {
    // Browser globals (root is window)
    if (!root.AsposeimagingCloudApiReference) {
      root.AsposeimagingCloudApiReference = {};
    }
    root.AsposeimagingCloudApiReference.DeconvolutionFilterProperties = factory(root.AsposeimagingCloudApiReference.ApiClient, root.AsposeimagingCloudApiReference.FilterPropertiesBase);
  }
}(this, function(ApiClient, FilterPropertiesBase) {
  'use strict';




  /**
   * The DeconvolutionFilterProperties model module.
   * @module model/DeconvolutionFilterProperties
   * @version 3.0
   */

  /**
   * Constructs a new <code>DeconvolutionFilterProperties</code>.
   * Deconvolution Filter Options, abstract class
   * @alias module:model/DeconvolutionFilterProperties
   * @class
   * @extends module:model/FilterPropertiesBase
   * @param discriminator {String} 
   * @param snr {Number} Gets or sets the SNR(signal-to-noise ratio) recommended range 0.002 - 0.009, default value = 0.007
   * @param brightness {Number} Gets or sets the brightness. recommended range 1 - 1.5 default value = 1.15
   * @param grayscale {Boolean} Gets or sets a value indicating whether this DeconvolutionFilterProperties is grayscale. Return grayscale mode or RGB mode.
   * @param isPartialLoaded {Boolean} Gets a value indicating whether this instance is partial loaded.
   */
  var exports = function(discriminator, snr, brightness, grayscale, isPartialLoaded) {
    var _this = this;
    FilterPropertiesBase.call(_this, discriminator);
    _this['Snr'] = snr;
    _this['Brightness'] = brightness;
    _this['Grayscale'] = grayscale;
    _this['IsPartialLoaded'] = isPartialLoaded;
  };

  /**
   * Constructs a <code>DeconvolutionFilterProperties</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DeconvolutionFilterProperties} obj Optional instance to populate.
   * @return {module:model/DeconvolutionFilterProperties} The populated <code>DeconvolutionFilterProperties</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      FilterPropertiesBase.constructFromObject(data, obj);
      if (data.hasOwnProperty('Snr')) {
        obj['Snr'] = ApiClient.convertToType(data['Snr'], 'Number');
      }
      if (data.hasOwnProperty('Brightness')) {
        obj['Brightness'] = ApiClient.convertToType(data['Brightness'], 'Number');
      }
      if (data.hasOwnProperty('Grayscale')) {
        obj['Grayscale'] = ApiClient.convertToType(data['Grayscale'], 'Boolean');
      }
      if (data.hasOwnProperty('IsPartialLoaded')) {
        obj['IsPartialLoaded'] = ApiClient.convertToType(data['IsPartialLoaded'], 'Boolean');
      }
    }
    return obj;
  }

  exports.prototype = Object.create(FilterPropertiesBase.prototype);
  exports.prototype.constructor = exports;

  /**
   * Gets or sets the SNR(signal-to-noise ratio) recommended range 0.002 - 0.009, default value = 0.007
   * @member {Number} Snr
   */
  exports.prototype['Snr'] = undefined;
  /**
   * Gets or sets the brightness. recommended range 1 - 1.5 default value = 1.15
   * @member {Number} Brightness
   */
  exports.prototype['Brightness'] = undefined;
  /**
   * Gets or sets a value indicating whether this DeconvolutionFilterProperties is grayscale. Return grayscale mode or RGB mode.
   * @member {Boolean} Grayscale
   */
  exports.prototype['Grayscale'] = undefined;
  /**
   * Gets a value indicating whether this instance is partial loaded.
   * @member {Boolean} IsPartialLoaded
   */
  exports.prototype['IsPartialLoaded'] = undefined;



  return exports;
}));


