/**
 * Aspose.Imaging Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Rectangle'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Rectangle'));
  } else {
    // Browser globals (root is window)
    if (!root.AsposeimagingCloudApiReference) {
      root.AsposeimagingCloudApiReference = {};
    }
    root.AsposeimagingCloudApiReference.DetectedObject = factory(root.AsposeimagingCloudApiReference.ApiClient, root.AsposeimagingCloudApiReference.Rectangle);
  }
}(this, function(ApiClient, Rectangle) {
  'use strict';




  /**
   * The DetectedObject model module.
   * @module model/DetectedObject
   * @version 3.0
   */

  /**
   * Constructs a new <code>DetectedObject</code>.
   * @alias module:model/DetectedObject
   * @class
   * @param score {Number} 
   * @param bounds {module:model/Rectangle} 
   */
  var exports = function(score, bounds) {
    var _this = this;


    _this['Score'] = score;
    _this['Bounds'] = bounds;
  };

  /**
   * Constructs a <code>DetectedObject</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DetectedObject} obj Optional instance to populate.
   * @return {module:model/DetectedObject} The populated <code>DetectedObject</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Label')) {
        obj['Label'] = ApiClient.convertToType(data['Label'], 'String');
      }
      if (data.hasOwnProperty('Score')) {
        obj['Score'] = ApiClient.convertToType(data['Score'], 'Number');
      }
      if (data.hasOwnProperty('Bounds')) {
        obj['Bounds'] = Rectangle.constructFromObject(data['Bounds']);
      }
    }
    return obj;
  }

  /**
   * @member {String} Label
   */
  exports.prototype['Label'] = undefined;
  /**
   * @member {Number} Score
   */
  exports.prototype['Score'] = undefined;
  /**
   * @member {module:model/Rectangle} Bounds
   */
  exports.prototype['Bounds'] = undefined;



  return exports;
}));


