/**
 * Aspose.Imaging Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AsposeimagingCloudApiReference) {
      root.AsposeimagingCloudApiReference = {};
    }
    root.AsposeimagingCloudApiReference.DiscUsage = factory(root.AsposeimagingCloudApiReference.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DiscUsage model module.
   * @module model/DiscUsage
   * @version 3.0
   */

  /**
   * Constructs a new <code>DiscUsage</code>.
   * Class for disc space information.
   * @alias module:model/DiscUsage
   * @class
   * @param usedSize {Number} Application used disc space.
   * @param totalSize {Number} Total disc space.
   */
  var exports = function(usedSize, totalSize) {
    var _this = this;

    _this['UsedSize'] = usedSize;
    _this['TotalSize'] = totalSize;
  };

  /**
   * Constructs a <code>DiscUsage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DiscUsage} obj Optional instance to populate.
   * @return {module:model/DiscUsage} The populated <code>DiscUsage</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('UsedSize')) {
        obj['UsedSize'] = ApiClient.convertToType(data['UsedSize'], 'Number');
      }
      if (data.hasOwnProperty('TotalSize')) {
        obj['TotalSize'] = ApiClient.convertToType(data['TotalSize'], 'Number');
      }
    }
    return obj;
  }

  /**
   * Application used disc space.
   * @member {Number} UsedSize
   */
  exports.prototype['UsedSize'] = undefined;
  /**
   * Total disc space.
   * @member {Number} TotalSize
   */
  exports.prototype['TotalSize'] = undefined;



  return exports;
}));


