/**
 * Aspose.Imaging Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AsposeimagingCloudApiReference) {
      root.AsposeimagingCloudApiReference = {};
    }
    root.AsposeimagingCloudApiReference.DjvuProperties = factory(root.AsposeimagingCloudApiReference.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DjvuProperties model module.
   * @module model/DjvuProperties
   * @version 3.0
   */

  /**
   * Constructs a new <code>DjvuProperties</code>.
   * Represents properties of djvu file.
   * @alias module:model/DjvuProperties
   * @class
   * @param hasBackgroundColor {Boolean} Gets or sets a value indicating whether background color is used.
   * @param pagesCount {Number} Gets or sets pages count.
   */
  var exports = function(hasBackgroundColor, pagesCount) {
    var _this = this;


    _this['HasBackgroundColor'] = hasBackgroundColor;
    _this['PagesCount'] = pagesCount;
  };

  /**
   * Constructs a <code>DjvuProperties</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DjvuProperties} obj Optional instance to populate.
   * @return {module:model/DjvuProperties} The populated <code>DjvuProperties</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('BackgroundColor')) {
        obj['BackgroundColor'] = ApiClient.convertToType(data['BackgroundColor'], 'String');
      }
      if (data.hasOwnProperty('HasBackgroundColor')) {
        obj['HasBackgroundColor'] = ApiClient.convertToType(data['HasBackgroundColor'], 'Boolean');
      }
      if (data.hasOwnProperty('PagesCount')) {
        obj['PagesCount'] = ApiClient.convertToType(data['PagesCount'], 'Number');
      }
    }
    return obj;
  }

  /**
   * Gets or sets background color.
   * @member {String} BackgroundColor
   */
  exports.prototype['BackgroundColor'] = undefined;
  /**
   * Gets or sets a value indicating whether background color is used.
   * @member {Boolean} HasBackgroundColor
   */
  exports.prototype['HasBackgroundColor'] = undefined;
  /**
   * Gets or sets pages count.
   * @member {Number} PagesCount
   */
  exports.prototype['PagesCount'] = undefined;



  return exports;
}));


