/**
 * Aspose.Imaging Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AsposeimagingCloudApiReference) {
      root.AsposeimagingCloudApiReference = {};
    }
    root.AsposeimagingCloudApiReference.EpsProperties = factory(root.AsposeimagingCloudApiReference.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The EpsProperties model module.
   * @module model/EpsProperties
   * @version 3.0
   */

  /**
   * Constructs a new <code>EpsProperties</code>.
   * @alias module:model/EpsProperties
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>EpsProperties</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EpsProperties} obj Optional instance to populate.
   * @return {module:model/EpsProperties} The populated <code>EpsProperties</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('BoundingBoxString')) {
        obj['BoundingBoxString'] = ApiClient.convertToType(data['BoundingBoxString'], 'String');
      }
      if (data.hasOwnProperty('CreationDateString')) {
        obj['CreationDateString'] = ApiClient.convertToType(data['CreationDateString'], 'String');
      }
      if (data.hasOwnProperty('Creator')) {
        obj['Creator'] = ApiClient.convertToType(data['Creator'], 'String');
      }
      if (data.hasOwnProperty('PostScriptVersion')) {
        obj['PostScriptVersion'] = ApiClient.convertToType(data['PostScriptVersion'], 'String');
      }
      if (data.hasOwnProperty('Title')) {
        obj['Title'] = ApiClient.convertToType(data['Title'], 'String');
      }
    }
    return obj;
  }

  /**
   * Gets the BoundingBox.
   * @member {String} BoundingBoxString
   */
  exports.prototype['BoundingBoxString'] = undefined;
  /**
   * Gets the CreationDate.
   * @member {String} CreationDateString
   */
  exports.prototype['CreationDateString'] = undefined;
  /**
   * Gets the Creator.
   * @member {String} Creator
   */
  exports.prototype['Creator'] = undefined;
  /**
   * Gets the PostScript version.
   * @member {String} PostScriptVersion
   */
  exports.prototype['PostScriptVersion'] = undefined;
  /**
   * Gets the Title.
   * @member {String} Title
   */
  exports.prototype['Title'] = undefined;



  return exports;
}));


