/**
 * Aspose.Imaging Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ErrorDetails'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ErrorDetails'));
  } else {
    // Browser globals (root is window)
    if (!root.AsposeimagingCloudApiReference) {
      root.AsposeimagingCloudApiReference = {};
    }
    root.AsposeimagingCloudApiReference.Error = factory(root.AsposeimagingCloudApiReference.ApiClient, root.AsposeimagingCloudApiReference.ErrorDetails);
  }
}(this, function(ApiClient, ErrorDetails) {
  'use strict';




  /**
   * The Error model module.
   * @module model/Error
   * @version 3.0
   */

  /**
   * Constructs a new <code>Error</code>.
   * Error
   * @alias module:model/Error
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>Error</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Error} obj Optional instance to populate.
   * @return {module:model/Error} The populated <code>Error</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Code')) {
        obj['Code'] = ApiClient.convertToType(data['Code'], 'String');
      }
      if (data.hasOwnProperty('Message')) {
        obj['Message'] = ApiClient.convertToType(data['Message'], 'String');
      }
      if (data.hasOwnProperty('Description')) {
        obj['Description'] = ApiClient.convertToType(data['Description'], 'String');
      }
      if (data.hasOwnProperty('InnerError')) {
        obj['InnerError'] = ErrorDetails.constructFromObject(data['InnerError']);
      }
    }
    return obj;
  }

  /**
   * Code             
   * @member {String} Code
   */
  exports.prototype['Code'] = undefined;
  /**
   * Message             
   * @member {String} Message
   */
  exports.prototype['Message'] = undefined;
  /**
   * Description             
   * @member {String} Description
   */
  exports.prototype['Description'] = undefined;
  /**
   * Inner Error             
   * @member {module:model/ErrorDetails} InnerError
   */
  exports.prototype['InnerError'] = undefined;



  return exports;
}));


