/**
 * Aspose.Imaging Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AsposeimagingCloudApiReference) {
      root.AsposeimagingCloudApiReference = {};
    }
    root.AsposeimagingCloudApiReference.ErrorDetails = factory(root.AsposeimagingCloudApiReference.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ErrorDetails model module.
   * @module model/ErrorDetails
   * @version 3.0
   */

  /**
   * Constructs a new <code>ErrorDetails</code>.
   * The error details
   * @alias module:model/ErrorDetails
   * @class
   * @param _date {Date} Date
   */
  var exports = function(_date) {
    var _this = this;


    _this['Date'] = _date;
  };

  /**
   * Constructs a <code>ErrorDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ErrorDetails} obj Optional instance to populate.
   * @return {module:model/ErrorDetails} The populated <code>ErrorDetails</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('RequestId')) {
        obj['RequestId'] = ApiClient.convertToType(data['RequestId'], 'String');
      }
      if (data.hasOwnProperty('Date')) {
        obj['Date'] = ApiClient.convertToType(data['Date'], 'Date');
      }
    }
    return obj;
  }

  /**
   * The request id
   * @member {String} RequestId
   */
  exports.prototype['RequestId'] = undefined;
  /**
   * Date
   * @member {Date} Date
   */
  exports.prototype['Date'] = undefined;



  return exports;
}));


