/**
 * Aspose.Imaging Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/StorageFile'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./StorageFile'));
  } else {
    // Browser globals (root is window)
    if (!root.AsposeimagingCloudApiReference) {
      root.AsposeimagingCloudApiReference = {};
    }
    root.AsposeimagingCloudApiReference.FileVersion = factory(root.AsposeimagingCloudApiReference.ApiClient, root.AsposeimagingCloudApiReference.StorageFile);
  }
}(this, function(ApiClient, StorageFile) {
  'use strict';




  /**
   * The FileVersion model module.
   * @module model/FileVersion
   * @version 3.0
   */

  /**
   * Constructs a new <code>FileVersion</code>.
   * File Version
   * @alias module:model/FileVersion
   * @class
   * @extends module:model/StorageFile
   * @param isFolder {Boolean} True if it is a folder.
   * @param size {Number} File or folder size.
   * @param isLatest {Boolean} Specifies whether the file is (true) or is not (false) the latest version of an file.
   */
  var exports = function(isFolder, size, isLatest) {
    var _this = this;
    StorageFile.call(_this, isFolder, size);

    _this['IsLatest'] = isLatest;
  };

  /**
   * Constructs a <code>FileVersion</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FileVersion} obj Optional instance to populate.
   * @return {module:model/FileVersion} The populated <code>FileVersion</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      StorageFile.constructFromObject(data, obj);
      if (data.hasOwnProperty('VersionId')) {
        obj['VersionId'] = ApiClient.convertToType(data['VersionId'], 'String');
      }
      if (data.hasOwnProperty('IsLatest')) {
        obj['IsLatest'] = ApiClient.convertToType(data['IsLatest'], 'Boolean');
      }
    }
    return obj;
  }

  exports.prototype = Object.create(StorageFile.prototype);
  exports.prototype.constructor = exports;

  /**
   * File Version ID.
   * @member {String} VersionId
   */
  exports.prototype['VersionId'] = undefined;
  /**
   * Specifies whether the file is (true) or is not (false) the latest version of an file.
   * @member {Boolean} IsLatest
   */
  exports.prototype['IsLatest'] = undefined;



  return exports;
}));


