/**
 * Aspose.Imaging Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/StorageFile'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./StorageFile'));
  } else {
    // Browser globals (root is window)
    if (!root.AsposeimagingCloudApiReference) {
      root.AsposeimagingCloudApiReference = {};
    }
    root.AsposeimagingCloudApiReference.FilesList = factory(root.AsposeimagingCloudApiReference.ApiClient, root.AsposeimagingCloudApiReference.StorageFile);
  }
}(this, function(ApiClient, StorageFile) {
  'use strict';




  /**
   * The FilesList model module.
   * @module model/FilesList
   * @version 3.0
   */

  /**
   * Constructs a new <code>FilesList</code>.
   * Files list
   * @alias module:model/FilesList
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>FilesList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FilesList} obj Optional instance to populate.
   * @return {module:model/FilesList} The populated <code>FilesList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Value')) {
        obj['Value'] = ApiClient.convertToType(data['Value'], [StorageFile]);
      }
    }
    return obj;
  }

  /**
   * Files and folders contained by folder StorageFile.
   * @member {Array.<module:model/StorageFile>} Value
   */
  exports.prototype['Value'] = undefined;



  return exports;
}));


