/**
 * Aspose.Imaging Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Error'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Error'));
  } else {
    // Browser globals (root is window)
    if (!root.AsposeimagingCloudApiReference) {
      root.AsposeimagingCloudApiReference = {};
    }
    root.AsposeimagingCloudApiReference.FilesUploadResult = factory(root.AsposeimagingCloudApiReference.ApiClient, root.AsposeimagingCloudApiReference.Error);
  }
}(this, function(ApiClient, Error) {
  'use strict';




  /**
   * The FilesUploadResult model module.
   * @module model/FilesUploadResult
   * @version 3.0
   */

  /**
   * Constructs a new <code>FilesUploadResult</code>.
   * File upload result
   * @alias module:model/FilesUploadResult
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>FilesUploadResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FilesUploadResult} obj Optional instance to populate.
   * @return {module:model/FilesUploadResult} The populated <code>FilesUploadResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Uploaded')) {
        obj['Uploaded'] = ApiClient.convertToType(data['Uploaded'], ['String']);
      }
      if (data.hasOwnProperty('Errors')) {
        obj['Errors'] = ApiClient.convertToType(data['Errors'], [Error]);
      }
    }
    return obj;
  }

  /**
   * List of uploaded file names
   * @member {Array.<String>} Uploaded
   */
  exports.prototype['Uploaded'] = undefined;
  /**
   * List of errors.
   * @member {Array.<module:model/Error>} Errors
   */
  exports.prototype['Errors'] = undefined;



  return exports;
}));


