/**
 * Aspose.Imaging Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DeconvolutionFilterProperties'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DeconvolutionFilterProperties'));
  } else {
    // Browser globals (root is window)
    if (!root.AsposeimagingCloudApiReference) {
      root.AsposeimagingCloudApiReference = {};
    }
    root.AsposeimagingCloudApiReference.GaussWienerFilterProperties = factory(root.AsposeimagingCloudApiReference.ApiClient, root.AsposeimagingCloudApiReference.DeconvolutionFilterProperties);
  }
}(this, function(ApiClient, DeconvolutionFilterProperties) {
  'use strict';




  /**
   * The GaussWienerFilterProperties model module.
   * @module model/GaussWienerFilterProperties
   * @version 3.0
   */

  /**
   * Constructs a new <code>GaussWienerFilterProperties</code>.
   * Gauss Wiener Filter Options Deblur gauss
   * @alias module:model/GaussWienerFilterProperties
   * @class
   * @extends module:model/DeconvolutionFilterProperties
   * @param discriminator {String} 
   * @param snr {Number} Gets or sets the SNR(signal-to-noise ratio) recommended range 0.002 - 0.009, default value = 0.007
   * @param brightness {Number} Gets or sets the brightness. recommended range 1 - 1.5 default value = 1.15
   * @param grayscale {Boolean} Gets or sets a value indicating whether this DeconvolutionFilterProperties is grayscale. Return grayscale mode or RGB mode.
   * @param isPartialLoaded {Boolean} Gets a value indicating whether this instance is partial loaded.
   * @param radius {Number} Gets or sets the radius.
   * @param smooth {Number} Gets or sets the smooth.
   */
  var exports = function(discriminator, snr, brightness, grayscale, isPartialLoaded, radius, smooth) {
    var _this = this;
    DeconvolutionFilterProperties.call(_this, discriminator, snr, brightness, grayscale, isPartialLoaded);
    _this['Radius'] = radius;
    _this['Smooth'] = smooth;
  };

  /**
   * Constructs a <code>GaussWienerFilterProperties</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GaussWienerFilterProperties} obj Optional instance to populate.
   * @return {module:model/GaussWienerFilterProperties} The populated <code>GaussWienerFilterProperties</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      DeconvolutionFilterProperties.constructFromObject(data, obj);
      if (data.hasOwnProperty('Radius')) {
        obj['Radius'] = ApiClient.convertToType(data['Radius'], 'Number');
      }
      if (data.hasOwnProperty('Smooth')) {
        obj['Smooth'] = ApiClient.convertToType(data['Smooth'], 'Number');
      }
    }
    return obj;
  }

  exports.prototype = Object.create(DeconvolutionFilterProperties.prototype);
  exports.prototype.constructor = exports;

  /**
   * Gets or sets the radius.
   * @member {Number} Radius
   */
  exports.prototype['Radius'] = undefined;
  /**
   * Gets or sets the smooth.
   * @member {Number} Smooth
   */
  exports.prototype['Smooth'] = undefined;



  return exports;
}));


