/**
 * Aspose.Imaging Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AsposeimagingCloudApiReference) {
      root.AsposeimagingCloudApiReference = {};
    }
    root.AsposeimagingCloudApiReference.GifProperties = factory(root.AsposeimagingCloudApiReference.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GifProperties model module.
   * @module model/GifProperties
   * @version 3.0
   */

  /**
   * Constructs a new <code>GifProperties</code>.
   * Represents information about image in GIF format.
   * @alias module:model/GifProperties
   * @class
   * @param hasBackgroundColor {Boolean} Gets or sets a value indicating whether background color is used.
   * @param hasTrailer {Boolean} Gets or sets a value indicating whether image has trailer.
   * @param pixelAspectRatio {Number} Gets or sets the pixel aspect ratio.
   */
  var exports = function(hasBackgroundColor, hasTrailer, pixelAspectRatio) {
    var _this = this;


    _this['HasBackgroundColor'] = hasBackgroundColor;
    _this['HasTrailer'] = hasTrailer;
    _this['PixelAspectRatio'] = pixelAspectRatio;
  };

  /**
   * Constructs a <code>GifProperties</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GifProperties} obj Optional instance to populate.
   * @return {module:model/GifProperties} The populated <code>GifProperties</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('BackgroundColor')) {
        obj['BackgroundColor'] = ApiClient.convertToType(data['BackgroundColor'], 'String');
      }
      if (data.hasOwnProperty('HasBackgroundColor')) {
        obj['HasBackgroundColor'] = ApiClient.convertToType(data['HasBackgroundColor'], 'Boolean');
      }
      if (data.hasOwnProperty('HasTrailer')) {
        obj['HasTrailer'] = ApiClient.convertToType(data['HasTrailer'], 'Boolean');
      }
      if (data.hasOwnProperty('PixelAspectRatio')) {
        obj['PixelAspectRatio'] = ApiClient.convertToType(data['PixelAspectRatio'], 'Number');
      }
    }
    return obj;
  }

  /**
   * Gets or sets the background color.
   * @member {String} BackgroundColor
   */
  exports.prototype['BackgroundColor'] = undefined;
  /**
   * Gets or sets a value indicating whether background color is used.
   * @member {Boolean} HasBackgroundColor
   */
  exports.prototype['HasBackgroundColor'] = undefined;
  /**
   * Gets or sets a value indicating whether image has trailer.
   * @member {Boolean} HasTrailer
   */
  exports.prototype['HasTrailer'] = undefined;
  /**
   * Gets or sets the pixel aspect ratio.
   * @member {Number} PixelAspectRatio
   */
  exports.prototype['PixelAspectRatio'] = undefined;



  return exports;
}));


