/**
 * Aspose.Imaging Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/BmpProperties', 'model/DicomProperties', 'model/DjvuProperties', 'model/DngProperties', 'model/EpsProperties', 'model/GifProperties', 'model/Jpeg2000Properties', 'model/JpegProperties', 'model/OdgProperties', 'model/PngProperties', 'model/PsdProperties', 'model/SvgProperties', 'model/TiffProperties', 'model/WebPProperties'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BmpProperties'), require('./DicomProperties'), require('./DjvuProperties'), require('./DngProperties'), require('./EpsProperties'), require('./GifProperties'), require('./Jpeg2000Properties'), require('./JpegProperties'), require('./OdgProperties'), require('./PngProperties'), require('./PsdProperties'), require('./SvgProperties'), require('./TiffProperties'), require('./WebPProperties'));
  } else {
    // Browser globals (root is window)
    if (!root.AsposeimagingCloudApiReference) {
      root.AsposeimagingCloudApiReference = {};
    }
    root.AsposeimagingCloudApiReference.ImagingResponse = factory(root.AsposeimagingCloudApiReference.ApiClient, root.AsposeimagingCloudApiReference.BmpProperties, root.AsposeimagingCloudApiReference.DicomProperties, root.AsposeimagingCloudApiReference.DjvuProperties, root.AsposeimagingCloudApiReference.DngProperties, root.AsposeimagingCloudApiReference.EpsProperties, root.AsposeimagingCloudApiReference.GifProperties, root.AsposeimagingCloudApiReference.Jpeg2000Properties, root.AsposeimagingCloudApiReference.JpegProperties, root.AsposeimagingCloudApiReference.OdgProperties, root.AsposeimagingCloudApiReference.PngProperties, root.AsposeimagingCloudApiReference.PsdProperties, root.AsposeimagingCloudApiReference.SvgProperties, root.AsposeimagingCloudApiReference.TiffProperties, root.AsposeimagingCloudApiReference.WebPProperties);
  }
}(this, function(ApiClient, BmpProperties, DicomProperties, DjvuProperties, DngProperties, EpsProperties, GifProperties, Jpeg2000Properties, JpegProperties, OdgProperties, PngProperties, PsdProperties, SvgProperties, TiffProperties, WebPProperties) {
  'use strict';




  /**
   * The ImagingResponse model module.
   * @module model/ImagingResponse
   * @version 3.0
   */

  /**
   * Constructs a new <code>ImagingResponse</code>.
   * Represents information about image.
   * @alias module:model/ImagingResponse
   * @class
   * @param height {Number} Gets or sets the height of image.
   * @param width {Number} Gets or sets the width of image.
   * @param bitsPerPixel {Number} Gets or sets the bits per pixel for image.
   * @param horizontalResolution {Number} Gets or sets the horizontal resolution of an image.
   * @param verticalResolution {Number} Gets or sets the vertical resolution of an image.
   * @param isCached {Boolean} Gets or sets a value indicating whether image is cached.
   */
  var exports = function(height, width, bitsPerPixel, horizontalResolution, verticalResolution, isCached) {
    var _this = this;

    _this['Height'] = height;
    _this['Width'] = width;
    _this['BitsPerPixel'] = bitsPerPixel;














    _this['HorizontalResolution'] = horizontalResolution;
    _this['VerticalResolution'] = verticalResolution;
    _this['IsCached'] = isCached;
  };

  /**
   * Constructs a <code>ImagingResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ImagingResponse} obj Optional instance to populate.
   * @return {module:model/ImagingResponse} The populated <code>ImagingResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Height')) {
        obj['Height'] = ApiClient.convertToType(data['Height'], 'Number');
      }
      if (data.hasOwnProperty('Width')) {
        obj['Width'] = ApiClient.convertToType(data['Width'], 'Number');
      }
      if (data.hasOwnProperty('BitsPerPixel')) {
        obj['BitsPerPixel'] = ApiClient.convertToType(data['BitsPerPixel'], 'Number');
      }
      if (data.hasOwnProperty('BmpProperties')) {
        obj['BmpProperties'] = BmpProperties.constructFromObject(data['BmpProperties']);
      }
      if (data.hasOwnProperty('GifProperties')) {
        obj['GifProperties'] = GifProperties.constructFromObject(data['GifProperties']);
      }
      if (data.hasOwnProperty('JpegProperties')) {
        obj['JpegProperties'] = JpegProperties.constructFromObject(data['JpegProperties']);
      }
      if (data.hasOwnProperty('PngProperties')) {
        obj['PngProperties'] = PngProperties.constructFromObject(data['PngProperties']);
      }
      if (data.hasOwnProperty('TiffProperties')) {
        obj['TiffProperties'] = TiffProperties.constructFromObject(data['TiffProperties']);
      }
      if (data.hasOwnProperty('PsdProperties')) {
        obj['PsdProperties'] = PsdProperties.constructFromObject(data['PsdProperties']);
      }
      if (data.hasOwnProperty('DjvuProperties')) {
        obj['DjvuProperties'] = DjvuProperties.constructFromObject(data['DjvuProperties']);
      }
      if (data.hasOwnProperty('WebPProperties')) {
        obj['WebPProperties'] = WebPProperties.constructFromObject(data['WebPProperties']);
      }
      if (data.hasOwnProperty('Jpeg2000Properties')) {
        obj['Jpeg2000Properties'] = Jpeg2000Properties.constructFromObject(data['Jpeg2000Properties']);
      }
      if (data.hasOwnProperty('DicomProperties')) {
        obj['DicomProperties'] = DicomProperties.constructFromObject(data['DicomProperties']);
      }
      if (data.hasOwnProperty('DngProperties')) {
        obj['DngProperties'] = DngProperties.constructFromObject(data['DngProperties']);
      }
      if (data.hasOwnProperty('OdgProperties')) {
        obj['OdgProperties'] = OdgProperties.constructFromObject(data['OdgProperties']);
      }
      if (data.hasOwnProperty('SvgProperties')) {
        obj['SvgProperties'] = SvgProperties.constructFromObject(data['SvgProperties']);
      }
      if (data.hasOwnProperty('EpsProperties')) {
        obj['EpsProperties'] = EpsProperties.constructFromObject(data['EpsProperties']);
      }
      if (data.hasOwnProperty('HorizontalResolution')) {
        obj['HorizontalResolution'] = ApiClient.convertToType(data['HorizontalResolution'], 'Number');
      }
      if (data.hasOwnProperty('VerticalResolution')) {
        obj['VerticalResolution'] = ApiClient.convertToType(data['VerticalResolution'], 'Number');
      }
      if (data.hasOwnProperty('IsCached')) {
        obj['IsCached'] = ApiClient.convertToType(data['IsCached'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * Gets or sets the height of image.
   * @member {Number} Height
   */
  exports.prototype['Height'] = undefined;
  /**
   * Gets or sets the width of image.
   * @member {Number} Width
   */
  exports.prototype['Width'] = undefined;
  /**
   * Gets or sets the bits per pixel for image.
   * @member {Number} BitsPerPixel
   */
  exports.prototype['BitsPerPixel'] = undefined;
  /**
   * Gets or sets the BMP properties.
   * @member {module:model/BmpProperties} BmpProperties
   */
  exports.prototype['BmpProperties'] = undefined;
  /**
   * Gets or sets the GIF properties.
   * @member {module:model/GifProperties} GifProperties
   */
  exports.prototype['GifProperties'] = undefined;
  /**
   * Gets or sets the JPEG properties.
   * @member {module:model/JpegProperties} JpegProperties
   */
  exports.prototype['JpegProperties'] = undefined;
  /**
   * Gets or sets the PNG properties.
   * @member {module:model/PngProperties} PngProperties
   */
  exports.prototype['PngProperties'] = undefined;
  /**
   * Gets or sets the TIFF properties.
   * @member {module:model/TiffProperties} TiffProperties
   */
  exports.prototype['TiffProperties'] = undefined;
  /**
   * Gets or sets the PSD properties.
   * @member {module:model/PsdProperties} PsdProperties
   */
  exports.prototype['PsdProperties'] = undefined;
  /**
   * Gets or sets the DJVU properties.
   * @member {module:model/DjvuProperties} DjvuProperties
   */
  exports.prototype['DjvuProperties'] = undefined;
  /**
   * Gets or sets the WEBP properties.
   * @member {module:model/WebPProperties} WebPProperties
   */
  exports.prototype['WebPProperties'] = undefined;
  /**
   * Gets or sets the JPEG2000 properties.
   * @member {module:model/Jpeg2000Properties} Jpeg2000Properties
   */
  exports.prototype['Jpeg2000Properties'] = undefined;
  /**
   * Gets or sets the DICOM properties.
   * @member {module:model/DicomProperties} DicomProperties
   */
  exports.prototype['DicomProperties'] = undefined;
  /**
   * Gets or sets the DNG properties.
   * @member {module:model/DngProperties} DngProperties
   */
  exports.prototype['DngProperties'] = undefined;
  /**
   * Gets or sets the the ODG properties.
   * @member {module:model/OdgProperties} OdgProperties
   */
  exports.prototype['OdgProperties'] = undefined;
  /**
   * Gets or sets the SVG properties.
   * @member {module:model/SvgProperties} SvgProperties
   */
  exports.prototype['SvgProperties'] = undefined;
  /**
   * Gets or sets the EPS properties.
   * @member {module:model/EpsProperties} EpsProperties
   */
  exports.prototype['EpsProperties'] = undefined;
  /**
   * Gets or sets the horizontal resolution of an image.
   * @member {Number} HorizontalResolution
   */
  exports.prototype['HorizontalResolution'] = undefined;
  /**
   * Gets or sets the vertical resolution of an image.
   * @member {Number} VerticalResolution
   */
  exports.prototype['VerticalResolution'] = undefined;
  /**
   * Gets or sets a value indicating whether image is cached.
   * @member {Boolean} IsCached
   */
  exports.prototype['IsCached'] = undefined;



  return exports;
}));


