/**
 * Aspose.Imaging Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AsposeimagingCloudApiReference) {
      root.AsposeimagingCloudApiReference = {};
    }
    root.AsposeimagingCloudApiReference.ImageFeatures = factory(root.AsposeimagingCloudApiReference.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ImageFeatures model module.
   * @module model/ImageFeatures
   * @version 3.0
   */

  /**
   * Constructs a new <code>ImageFeatures</code>.
   * Image features.
   * @alias module:model/ImageFeatures
   * @class
   * @param featuresCount {Number} Gets the features count.
   * @param featureLengthInBits {Number} Gets the feature length in bits.
   */
  var exports = function(featuresCount, featureLengthInBits) {
    var _this = this;


    _this['FeaturesCount'] = featuresCount;
    _this['FeatureLengthInBits'] = featureLengthInBits;

  };

  /**
   * Constructs a <code>ImageFeatures</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ImageFeatures} obj Optional instance to populate.
   * @return {module:model/ImageFeatures} The populated <code>ImageFeatures</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ImageId')) {
        obj['ImageId'] = ApiClient.convertToType(data['ImageId'], 'String');
      }
      if (data.hasOwnProperty('FeaturesCount')) {
        obj['FeaturesCount'] = ApiClient.convertToType(data['FeaturesCount'], 'Number');
      }
      if (data.hasOwnProperty('FeatureLengthInBits')) {
        obj['FeatureLengthInBits'] = ApiClient.convertToType(data['FeatureLengthInBits'], 'Number');
      }
      if (data.hasOwnProperty('Features')) {
        obj['Features'] = ApiClient.convertToType(data['Features'], 'Blob');
      }
    }
    return obj;
  }

  /**
   * Gets the image identifier.
   * @member {String} ImageId
   */
  exports.prototype['ImageId'] = undefined;
  /**
   * Gets the features count.
   * @member {Number} FeaturesCount
   */
  exports.prototype['FeaturesCount'] = undefined;
  /**
   * Gets the feature length in bits.
   * @member {Number} FeatureLengthInBits
   */
  exports.prototype['FeatureLengthInBits'] = undefined;
  /**
   * Gets the features.
   * @member {Blob} Features
   */
  exports.prototype['Features'] = undefined;



  return exports;
}));


