/**
 * Aspose.Imaging Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AsposeimagingCloudApiReference) {
      root.AsposeimagingCloudApiReference = {};
    }
    root.AsposeimagingCloudApiReference.JfifData = factory(root.AsposeimagingCloudApiReference.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The JfifData model module.
   * @module model/JfifData
   * @version 3.0
   */

  /**
   * Constructs a new <code>JfifData</code>.
   * Represents JFIF data.
   * @alias module:model/JfifData
   * @class
   * @param version {Number} Gets or sets the version.
   * @param xDensity {Number} Gets or sets the X density.
   * @param yDensity {Number} Gets or sets the Y density.
   */
  var exports = function(version, xDensity, yDensity) {
    var _this = this;


    _this['Version'] = version;
    _this['XDensity'] = xDensity;
    _this['YDensity'] = yDensity;
  };

  /**
   * Constructs a <code>JfifData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/JfifData} obj Optional instance to populate.
   * @return {module:model/JfifData} The populated <code>JfifData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('DensityUnits')) {
        obj['DensityUnits'] = ApiClient.convertToType(data['DensityUnits'], 'String');
      }
      if (data.hasOwnProperty('Version')) {
        obj['Version'] = ApiClient.convertToType(data['Version'], 'Number');
      }
      if (data.hasOwnProperty('XDensity')) {
        obj['XDensity'] = ApiClient.convertToType(data['XDensity'], 'Number');
      }
      if (data.hasOwnProperty('YDensity')) {
        obj['YDensity'] = ApiClient.convertToType(data['YDensity'], 'Number');
      }
    }
    return obj;
  }

  /**
   * Gets or sets the density units.
   * @member {String} DensityUnits
   */
  exports.prototype['DensityUnits'] = undefined;
  /**
   * Gets or sets the version.
   * @member {Number} Version
   */
  exports.prototype['Version'] = undefined;
  /**
   * Gets or sets the X density.
   * @member {Number} XDensity
   */
  exports.prototype['XDensity'] = undefined;
  /**
   * Gets or sets the Y density.
   * @member {Number} YDensity
   */
  exports.prototype['YDensity'] = undefined;



  return exports;
}));


