/**
 * Aspose.Imaging Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/FilterPropertiesBase'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./FilterPropertiesBase'));
  } else {
    // Browser globals (root is window)
    if (!root.AsposeimagingCloudApiReference) {
      root.AsposeimagingCloudApiReference = {};
    }
    root.AsposeimagingCloudApiReference.MedianFilterProperties = factory(root.AsposeimagingCloudApiReference.ApiClient, root.AsposeimagingCloudApiReference.FilterPropertiesBase);
  }
}(this, function(ApiClient, FilterPropertiesBase) {
  'use strict';




  /**
   * The MedianFilterProperties model module.
   * @module model/MedianFilterProperties
   * @version 3.0
   */

  /**
   * Constructs a new <code>MedianFilterProperties</code>.
   * Median filter
   * @alias module:model/MedianFilterProperties
   * @class
   * @extends module:model/FilterPropertiesBase
   * @param discriminator {String} 
   * @param size {Number} Gets or sets the size.
   */
  var exports = function(discriminator, size) {
    var _this = this;
    FilterPropertiesBase.call(_this, discriminator);
    _this['Size'] = size;
  };

  /**
   * Constructs a <code>MedianFilterProperties</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MedianFilterProperties} obj Optional instance to populate.
   * @return {module:model/MedianFilterProperties} The populated <code>MedianFilterProperties</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      FilterPropertiesBase.constructFromObject(data, obj);
      if (data.hasOwnProperty('Size')) {
        obj['Size'] = ApiClient.convertToType(data['Size'], 'Number');
      }
    }
    return obj;
  }

  exports.prototype = Object.create(FilterPropertiesBase.prototype);
  exports.prototype.constructor = exports;

  /**
   * Gets or sets the size.
   * @member {Number} Size
   */
  exports.prototype['Size'] = undefined;



  return exports;
}));


