/**
 * Aspose.Imaging Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AsposeimagingCloudApiReference) {
      root.AsposeimagingCloudApiReference = {};
    }
    root.AsposeimagingCloudApiReference.OdgMetadata = factory(root.AsposeimagingCloudApiReference.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The OdgMetadata model module.
   * @module model/OdgMetadata
   * @version 3.0
   */

  /**
   * Constructs a new <code>OdgMetadata</code>.
   * ODG format metadata
   * @alias module:model/OdgMetadata
   * @class
   */
  var exports = function() {
    var _this = this;



















  };

  /**
   * Constructs a <code>OdgMetadata</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OdgMetadata} obj Optional instance to populate.
   * @return {module:model/OdgMetadata} The populated <code>OdgMetadata</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Generator')) {
        obj['Generator'] = ApiClient.convertToType(data['Generator'], 'String');
      }
      if (data.hasOwnProperty('Title')) {
        obj['Title'] = ApiClient.convertToType(data['Title'], 'String');
      }
      if (data.hasOwnProperty('Description')) {
        obj['Description'] = ApiClient.convertToType(data['Description'], 'String');
      }
      if (data.hasOwnProperty('Subject')) {
        obj['Subject'] = ApiClient.convertToType(data['Subject'], 'String');
      }
      if (data.hasOwnProperty('Keywords')) {
        obj['Keywords'] = ApiClient.convertToType(data['Keywords'], 'String');
      }
      if (data.hasOwnProperty('InitialCreator')) {
        obj['InitialCreator'] = ApiClient.convertToType(data['InitialCreator'], 'String');
      }
      if (data.hasOwnProperty('Creator')) {
        obj['Creator'] = ApiClient.convertToType(data['Creator'], 'String');
      }
      if (data.hasOwnProperty('PrintedBy')) {
        obj['PrintedBy'] = ApiClient.convertToType(data['PrintedBy'], 'String');
      }
      if (data.hasOwnProperty('CreationDateTime')) {
        obj['CreationDateTime'] = ApiClient.convertToType(data['CreationDateTime'], 'String');
      }
      if (data.hasOwnProperty('ModificationDateTime')) {
        obj['ModificationDateTime'] = ApiClient.convertToType(data['ModificationDateTime'], 'String');
      }
      if (data.hasOwnProperty('PrintDateTime')) {
        obj['PrintDateTime'] = ApiClient.convertToType(data['PrintDateTime'], 'String');
      }
      if (data.hasOwnProperty('DocumentTemplate')) {
        obj['DocumentTemplate'] = ApiClient.convertToType(data['DocumentTemplate'], 'String');
      }
      if (data.hasOwnProperty('AutomaticReload')) {
        obj['AutomaticReload'] = ApiClient.convertToType(data['AutomaticReload'], 'String');
      }
      if (data.hasOwnProperty('HyperlinkBehavior')) {
        obj['HyperlinkBehavior'] = ApiClient.convertToType(data['HyperlinkBehavior'], 'String');
      }
      if (data.hasOwnProperty('Language')) {
        obj['Language'] = ApiClient.convertToType(data['Language'], 'String');
      }
      if (data.hasOwnProperty('EditingCycles')) {
        obj['EditingCycles'] = ApiClient.convertToType(data['EditingCycles'], 'String');
      }
      if (data.hasOwnProperty('EditingDuration')) {
        obj['EditingDuration'] = ApiClient.convertToType(data['EditingDuration'], 'String');
      }
      if (data.hasOwnProperty('DocumentStatistics')) {
        obj['DocumentStatistics'] = ApiClient.convertToType(data['DocumentStatistics'], 'String');
      }
    }
    return obj;
  }

  /**
   * Gets or sets the generator.
   * @member {String} Generator
   */
  exports.prototype['Generator'] = undefined;
  /**
   * Gets or sets the title.
   * @member {String} Title
   */
  exports.prototype['Title'] = undefined;
  /**
   * Gets or sets the description.
   * @member {String} Description
   */
  exports.prototype['Description'] = undefined;
  /**
   * Gets or sets the subject.
   * @member {String} Subject
   */
  exports.prototype['Subject'] = undefined;
  /**
   * Gets or sets the keywords.
   * @member {String} Keywords
   */
  exports.prototype['Keywords'] = undefined;
  /**
   * Gets or sets the initial creator.
   * @member {String} InitialCreator
   */
  exports.prototype['InitialCreator'] = undefined;
  /**
   * Gets or sets the creator.
   * @member {String} Creator
   */
  exports.prototype['Creator'] = undefined;
  /**
   * Gets or sets the \"PrintedBy\" record.
   * @member {String} PrintedBy
   */
  exports.prototype['PrintedBy'] = undefined;
  /**
   * Gets or sets the creation date and time.
   * @member {String} CreationDateTime
   */
  exports.prototype['CreationDateTime'] = undefined;
  /**
   * Gets or sets the modification date and time.
   * @member {String} ModificationDateTime
   */
  exports.prototype['ModificationDateTime'] = undefined;
  /**
   * Gets or sets the print date and time.
   * @member {String} PrintDateTime
   */
  exports.prototype['PrintDateTime'] = undefined;
  /**
   * Gets or sets the document template.
   * @member {String} DocumentTemplate
   */
  exports.prototype['DocumentTemplate'] = undefined;
  /**
   * Gets or sets the automatic reload.
   * @member {String} AutomaticReload
   */
  exports.prototype['AutomaticReload'] = undefined;
  /**
   * Gets or sets the hyperlink behavior.
   * @member {String} HyperlinkBehavior
   */
  exports.prototype['HyperlinkBehavior'] = undefined;
  /**
   * Gets or sets the language.
   * @member {String} Language
   */
  exports.prototype['Language'] = undefined;
  /**
   * Gets or sets the editing cycles.
   * @member {String} EditingCycles
   */
  exports.prototype['EditingCycles'] = undefined;
  /**
   * Gets or sets the duration of the editing.
   * @member {String} EditingDuration
   */
  exports.prototype['EditingDuration'] = undefined;
  /**
   * Gets or sets the document statistics.
   * @member {String} DocumentStatistics
   */
  exports.prototype['DocumentStatistics'] = undefined;



  return exports;
}));


