/**
 * Aspose.Imaging Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/OdgMetadata', 'model/OdgPage'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./OdgMetadata'), require('./OdgPage'));
  } else {
    // Browser globals (root is window)
    if (!root.AsposeimagingCloudApiReference) {
      root.AsposeimagingCloudApiReference = {};
    }
    root.AsposeimagingCloudApiReference.OdgProperties = factory(root.AsposeimagingCloudApiReference.ApiClient, root.AsposeimagingCloudApiReference.OdgMetadata, root.AsposeimagingCloudApiReference.OdgPage);
  }
}(this, function(ApiClient, OdgMetadata, OdgPage) {
  'use strict';




  /**
   * The OdgProperties model module.
   * @module model/OdgProperties
   * @version 3.0
   */

  /**
   * Constructs a new <code>OdgProperties</code>.
   * ODG format specific properties
   * @alias module:model/OdgProperties
   * @class
   * @param pageCount {Number} Gets or sets the page count.
   */
  var exports = function(pageCount) {
    var _this = this;

    _this['PageCount'] = pageCount;


  };

  /**
   * Constructs a <code>OdgProperties</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OdgProperties} obj Optional instance to populate.
   * @return {module:model/OdgProperties} The populated <code>OdgProperties</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('PageCount')) {
        obj['PageCount'] = ApiClient.convertToType(data['PageCount'], 'Number');
      }
      if (data.hasOwnProperty('Metadata')) {
        obj['Metadata'] = OdgMetadata.constructFromObject(data['Metadata']);
      }
      if (data.hasOwnProperty('Pages')) {
        obj['Pages'] = ApiClient.convertToType(data['Pages'], [OdgPage]);
      }
    }
    return obj;
  }

  /**
   * Gets or sets the page count.
   * @member {Number} PageCount
   */
  exports.prototype['PageCount'] = undefined;
  /**
   * Gets or sets the metadata.
   * @member {module:model/OdgMetadata} Metadata
   */
  exports.prototype['Metadata'] = undefined;
  /**
   * Gets or sets the pages.
   * @member {Array.<module:model/OdgPage>} Pages
   */
  exports.prototype['Pages'] = undefined;



  return exports;
}));


