/**
 * Aspose.Imaging Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AsposeimagingCloudApiReference) {
      root.AsposeimagingCloudApiReference = {};
    }
    root.AsposeimagingCloudApiReference.PsdProperties = factory(root.AsposeimagingCloudApiReference.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The PsdProperties model module.
   * @module model/PsdProperties
   * @version 3.0
   */

  /**
   * Constructs a new <code>PsdProperties</code>.
   * Represents information about PSD image
   * @alias module:model/PsdProperties
   * @class
   * @param bitsPerChannel {Number} Gets or sets the bits per channel.
   * @param channelsCount {Number} Gets or sets the channels count.
   */
  var exports = function(bitsPerChannel, channelsCount) {
    var _this = this;

    _this['BitsPerChannel'] = bitsPerChannel;
    _this['ChannelsCount'] = channelsCount;


  };

  /**
   * Constructs a <code>PsdProperties</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PsdProperties} obj Optional instance to populate.
   * @return {module:model/PsdProperties} The populated <code>PsdProperties</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('BitsPerChannel')) {
        obj['BitsPerChannel'] = ApiClient.convertToType(data['BitsPerChannel'], 'Number');
      }
      if (data.hasOwnProperty('ChannelsCount')) {
        obj['ChannelsCount'] = ApiClient.convertToType(data['ChannelsCount'], 'Number');
      }
      if (data.hasOwnProperty('ColorMode')) {
        obj['ColorMode'] = ApiClient.convertToType(data['ColorMode'], 'String');
      }
      if (data.hasOwnProperty('Compression')) {
        obj['Compression'] = ApiClient.convertToType(data['Compression'], 'String');
      }
    }
    return obj;
  }

  /**
   * Gets or sets the bits per channel.
   * @member {Number} BitsPerChannel
   */
  exports.prototype['BitsPerChannel'] = undefined;
  /**
   * Gets or sets the channels count.
   * @member {Number} ChannelsCount
   */
  exports.prototype['ChannelsCount'] = undefined;
  /**
   * Gets or sets the color mode.
   * @member {String} ColorMode
   */
  exports.prototype['ColorMode'] = undefined;
  /**
   * Gets or sets the compression.
   * @member {String} Compression
   */
  exports.prototype['Compression'] = undefined;



  return exports;
}));


