/**
 * Aspose.Imaging Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AsposeimagingCloudApiReference) {
      root.AsposeimagingCloudApiReference = {};
    }
    root.AsposeimagingCloudApiReference.SearchResult = factory(root.AsposeimagingCloudApiReference.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SearchResult model module.
   * @module model/SearchResult
   * @version 3.0
   */

  /**
   * Constructs a new <code>SearchResult</code>.
   * Image search result.
   * @alias module:model/SearchResult
   * @class
   * @param similarity {Number} Gets or sets the similarity.
   */
  var exports = function(similarity) {
    var _this = this;


    _this['Similarity'] = similarity;
  };

  /**
   * Constructs a <code>SearchResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SearchResult} obj Optional instance to populate.
   * @return {module:model/SearchResult} The populated <code>SearchResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('ImageId')) {
        obj['ImageId'] = ApiClient.convertToType(data['ImageId'], 'String');
      }
      if (data.hasOwnProperty('Similarity')) {
        obj['Similarity'] = ApiClient.convertToType(data['Similarity'], 'Number');
      }
    }
    return obj;
  }

  /**
   * Gets or sets the image identifier.
   * @member {String} ImageId
   */
  exports.prototype['ImageId'] = undefined;
  /**
   * Gets or sets the similarity.
   * @member {Number} Similarity
   */
  exports.prototype['Similarity'] = undefined;



  return exports;
}));


