/**
 * Aspose.Imaging Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AsposeimagingCloudApiReference) {
      root.AsposeimagingCloudApiReference = {};
    }
    root.AsposeimagingCloudApiReference.SearchContextStatus = factory(root.AsposeimagingCloudApiReference.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SearchContextStatus model module.
   * @module model/SearchContextStatus
   * @version 3.0
   */

  /**
   * Constructs a new <code>SearchContextStatus</code>.
   * Search context status.
   * @alias module:model/SearchContextStatus
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>SearchContextStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SearchContextStatus} obj Optional instance to populate.
   * @return {module:model/SearchContextStatus} The populated <code>SearchContextStatus</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Id')) {
        obj['Id'] = ApiClient.convertToType(data['Id'], 'String');
      }
      if (data.hasOwnProperty('SearchStatus')) {
        obj['SearchStatus'] = ApiClient.convertToType(data['SearchStatus'], 'String');
      }
    }
    return obj;
  }

  /**
   * Gets or sets the identifier.
   * @member {String} Id
   */
  exports.prototype['Id'] = undefined;
  /**
   * Gets or sets the status.
   * @member {String} SearchStatus
   */
  exports.prototype['SearchStatus'] = undefined;



  return exports;
}));


