/**
 * Aspose.Imaging Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ConvolutionFilterProperties'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ConvolutionFilterProperties'));
  } else {
    // Browser globals (root is window)
    if (!root.AsposeimagingCloudApiReference) {
      root.AsposeimagingCloudApiReference = {};
    }
    root.AsposeimagingCloudApiReference.SharpenFilterProperties = factory(root.AsposeimagingCloudApiReference.ApiClient, root.AsposeimagingCloudApiReference.ConvolutionFilterProperties);
  }
}(this, function(ApiClient, ConvolutionFilterProperties) {
  'use strict';




  /**
   * The SharpenFilterProperties model module.
   * @module model/SharpenFilterProperties
   * @version 3.0
   */

  /**
   * Constructs a new <code>SharpenFilterProperties</code>.
   * The Sharpen filter options             
   * @alias module:model/SharpenFilterProperties
   * @class
   * @extends module:model/ConvolutionFilterProperties
   * @param discriminator {String} 
   * @param factor {Number} Gets or sets the factor.
   * @param bias {Number} Gets or sets the bias.
   * @param size {Number} Gets or sets the size.             
   * @param sigma {Number} Gets or sets the sigma.             
   */
  var exports = function(discriminator, factor, bias, size, sigma) {
    var _this = this;
    ConvolutionFilterProperties.call(_this, discriminator, factor, bias);
    _this['Size'] = size;
    _this['Sigma'] = sigma;
  };

  /**
   * Constructs a <code>SharpenFilterProperties</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SharpenFilterProperties} obj Optional instance to populate.
   * @return {module:model/SharpenFilterProperties} The populated <code>SharpenFilterProperties</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      ConvolutionFilterProperties.constructFromObject(data, obj);
      if (data.hasOwnProperty('Size')) {
        obj['Size'] = ApiClient.convertToType(data['Size'], 'Number');
      }
      if (data.hasOwnProperty('Sigma')) {
        obj['Sigma'] = ApiClient.convertToType(data['Sigma'], 'Number');
      }
    }
    return obj;
  }

  exports.prototype = Object.create(ConvolutionFilterProperties.prototype);
  exports.prototype.constructor = exports;

  /**
   * Gets or sets the size.             
   * @member {Number} Size
   */
  exports.prototype['Size'] = undefined;
  /**
   * Gets or sets the sigma.             
   * @member {Number} Sigma
   */
  exports.prototype['Sigma'] = undefined;



  return exports;
}));


