/**
 * Aspose.Imaging Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/FilterPropertiesBase'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./FilterPropertiesBase'));
  } else {
    // Browser globals (root is window)
    if (!root.AsposeimagingCloudApiReference) {
      root.AsposeimagingCloudApiReference = {};
    }
    root.AsposeimagingCloudApiReference.SmallRectangularFilterProperties = factory(root.AsposeimagingCloudApiReference.ApiClient, root.AsposeimagingCloudApiReference.FilterPropertiesBase);
  }
}(this, function(ApiClient, FilterPropertiesBase) {
  'use strict';




  /**
   * The SmallRectangularFilterProperties model module.
   * @module model/SmallRectangularFilterProperties
   * @version 3.0
   */

  /**
   * Constructs a new <code>SmallRectangularFilterProperties</code>.
   * Small rectangular filter options
   * @alias module:model/SmallRectangularFilterProperties
   * @class
   * @extends module:model/FilterPropertiesBase
   * @param discriminator {String} 
   */
  var exports = function(discriminator) {
    var _this = this;
    FilterPropertiesBase.call(_this, discriminator);
  };

  /**
   * Constructs a <code>SmallRectangularFilterProperties</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SmallRectangularFilterProperties} obj Optional instance to populate.
   * @return {module:model/SmallRectangularFilterProperties} The populated <code>SmallRectangularFilterProperties</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      FilterPropertiesBase.constructFromObject(data, obj);
    }
    return obj;
  }

  exports.prototype = Object.create(FilterPropertiesBase.prototype);
  exports.prototype.constructor = exports;




  return exports;
}));


