/**
 * Aspose.Imaging Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AsposeimagingCloudApiReference) {
      root.AsposeimagingCloudApiReference = {};
    }
    root.AsposeimagingCloudApiReference.StorageExist = factory(root.AsposeimagingCloudApiReference.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The StorageExist model module.
   * @module model/StorageExist
   * @version 3.0
   */

  /**
   * Constructs a new <code>StorageExist</code>.
   * Storage exists
   * @alias module:model/StorageExist
   * @class
   * @param exists {Boolean} Shows that the storage exists.             
   */
  var exports = function(exists) {
    var _this = this;

    _this['Exists'] = exists;
  };

  /**
   * Constructs a <code>StorageExist</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StorageExist} obj Optional instance to populate.
   * @return {module:model/StorageExist} The populated <code>StorageExist</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Exists')) {
        obj['Exists'] = ApiClient.convertToType(data['Exists'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * Shows that the storage exists.             
   * @member {Boolean} Exists
   */
  exports.prototype['Exists'] = undefined;



  return exports;
}));


