/**
 * Aspose.Imaging Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ExifData', 'model/TiffFrame'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ExifData'), require('./TiffFrame'));
  } else {
    // Browser globals (root is window)
    if (!root.AsposeimagingCloudApiReference) {
      root.AsposeimagingCloudApiReference = {};
    }
    root.AsposeimagingCloudApiReference.TiffProperties = factory(root.AsposeimagingCloudApiReference.ApiClient, root.AsposeimagingCloudApiReference.ExifData, root.AsposeimagingCloudApiReference.TiffFrame);
  }
}(this, function(ApiClient, ExifData, TiffFrame) {
  'use strict';




  /**
   * The TiffProperties model module.
   * @module model/TiffProperties
   * @version 3.0
   */

  /**
   * Constructs a new <code>TiffProperties</code>.
   * Represents properties of TIFF image.
   * @alias module:model/TiffProperties
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>TiffProperties</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TiffProperties} obj Optional instance to populate.
   * @return {module:model/TiffProperties} The populated <code>TiffProperties</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Frames')) {
        obj['Frames'] = ApiClient.convertToType(data['Frames'], [TiffFrame]);
      }
      if (data.hasOwnProperty('ByteOrder')) {
        obj['ByteOrder'] = ApiClient.convertToType(data['ByteOrder'], 'String');
      }
      if (data.hasOwnProperty('ExifData')) {
        obj['ExifData'] = ExifData.constructFromObject(data['ExifData']);
      }
    }
    return obj;
  }

  /**
   * Frames information.
   * @member {Array.<module:model/TiffFrame>} Frames
   */
  exports.prototype['Frames'] = undefined;
  /**
   * Gets or sets the byte order.
   * @member {String} ByteOrder
   */
  exports.prototype['ByteOrder'] = undefined;
  /**
   * Gets or sets the EXIF data.
   * @member {module:model/ExifData} ExifData
   */
  exports.prototype['ExifData'] = undefined;



  return exports;
}));


