/**
 * Aspose.Imaging Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AsposeimagingCloudApiReference) {
      root.AsposeimagingCloudApiReference = {};
    }
    root.AsposeimagingCloudApiReference.WebPProperties = factory(root.AsposeimagingCloudApiReference.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The WebPProperties model module.
   * @module model/WebPProperties
   * @version 3.0
   */

  /**
   * Constructs a new <code>WebPProperties</code>.
   * Represents information about image in WEBP format.
   * @alias module:model/WebPProperties
   * @class
   * @param lossless {Boolean} Gets or sets a value indicating whether these WebPOptions is lossless.
   * @param quality {Number} Gets or sets the quality.
   * @param animLoopCount {Number} Gets or sets the animation loop count.
   * @param animBackgroundColor {Number} Gets or sets the color of the animation background.
   */
  var exports = function(lossless, quality, animLoopCount, animBackgroundColor) {
    var _this = this;

    _this['Lossless'] = lossless;
    _this['Quality'] = quality;
    _this['AnimLoopCount'] = animLoopCount;
    _this['AnimBackgroundColor'] = animBackgroundColor;
  };

  /**
   * Constructs a <code>WebPProperties</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/WebPProperties} obj Optional instance to populate.
   * @return {module:model/WebPProperties} The populated <code>WebPProperties</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Lossless')) {
        obj['Lossless'] = ApiClient.convertToType(data['Lossless'], 'Boolean');
      }
      if (data.hasOwnProperty('Quality')) {
        obj['Quality'] = ApiClient.convertToType(data['Quality'], 'Number');
      }
      if (data.hasOwnProperty('AnimLoopCount')) {
        obj['AnimLoopCount'] = ApiClient.convertToType(data['AnimLoopCount'], 'Number');
      }
      if (data.hasOwnProperty('AnimBackgroundColor')) {
        obj['AnimBackgroundColor'] = ApiClient.convertToType(data['AnimBackgroundColor'], 'Number');
      }
    }
    return obj;
  }

  /**
   * Gets or sets a value indicating whether these WebPOptions is lossless.
   * @member {Boolean} Lossless
   */
  exports.prototype['Lossless'] = undefined;
  /**
   * Gets or sets the quality.
   * @member {Number} Quality
   */
  exports.prototype['Quality'] = undefined;
  /**
   * Gets or sets the animation loop count.
   * @member {Number} AnimLoopCount
   */
  exports.prototype['AnimLoopCount'] = undefined;
  /**
   * Gets or sets the color of the animation background.
   * @member {Number} AnimBackgroundColor
   */
  exports.prototype['AnimBackgroundColor'] = undefined;



  return exports;
}));


