/**
 * Aspose.Imaging Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AsposeimagingCloudApiReference);
  }
}(this, function(expect, AsposeimagingCloudApiReference) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AsposeimagingCloudApiReference.BilateralSmoothingFilterProperties();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BilateralSmoothingFilterProperties', function() {
    it('should create an instance of BilateralSmoothingFilterProperties', function() {
      // uncomment below and update the code to test BilateralSmoothingFilterProperties
      //var instance = new AsposeimagingCloudApiReference.BilateralSmoothingFilterProperties();
      //expect(instance).to.be.a(AsposeimagingCloudApiReference.BilateralSmoothingFilterProperties);
    });

    it('should have the property size (base name: "Size")', function() {
      // uncomment below and update the code to test the property size
      //var instance = new AsposeimagingCloudApiReference.BilateralSmoothingFilterProperties();
      //expect(instance).to.be();
    });

    it('should have the property spatialFactor (base name: "SpatialFactor")', function() {
      // uncomment below and update the code to test the property spatialFactor
      //var instance = new AsposeimagingCloudApiReference.BilateralSmoothingFilterProperties();
      //expect(instance).to.be();
    });

    it('should have the property spatialPower (base name: "SpatialPower")', function() {
      // uncomment below and update the code to test the property spatialPower
      //var instance = new AsposeimagingCloudApiReference.BilateralSmoothingFilterProperties();
      //expect(instance).to.be();
    });

    it('should have the property colorFactor (base name: "ColorFactor")', function() {
      // uncomment below and update the code to test the property colorFactor
      //var instance = new AsposeimagingCloudApiReference.BilateralSmoothingFilterProperties();
      //expect(instance).to.be();
    });

    it('should have the property colorPower (base name: "ColorPower")', function() {
      // uncomment below and update the code to test the property colorPower
      //var instance = new AsposeimagingCloudApiReference.BilateralSmoothingFilterProperties();
      //expect(instance).to.be();
    });

  });

}));
