/**
 * Aspose.Imaging Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AsposeimagingCloudApiReference);
  }
}(this, function(expect, AsposeimagingCloudApiReference) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AsposeimagingCloudApiReference.DngProperties();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DngProperties', function() {
    it('should create an instance of DngProperties', function() {
      // uncomment below and update the code to test DngProperties
      //var instance = new AsposeimagingCloudApiReference.DngProperties();
      //expect(instance).to.be.a(AsposeimagingCloudApiReference.DngProperties);
    });

    it('should have the property dngVersion (base name: "DngVersion")', function() {
      // uncomment below and update the code to test the property dngVersion
      //var instance = new AsposeimagingCloudApiReference.DngProperties();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "Description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new AsposeimagingCloudApiReference.DngProperties();
      //expect(instance).to.be();
    });

    it('should have the property model (base name: "Model")', function() {
      // uncomment below and update the code to test the property model
      //var instance = new AsposeimagingCloudApiReference.DngProperties();
      //expect(instance).to.be();
    });

    it('should have the property cameraManufacturer (base name: "CameraManufacturer")', function() {
      // uncomment below and update the code to test the property cameraManufacturer
      //var instance = new AsposeimagingCloudApiReference.DngProperties();
      //expect(instance).to.be();
    });

    it('should have the property isFoveon (base name: "IsFoveon")', function() {
      // uncomment below and update the code to test the property isFoveon
      //var instance = new AsposeimagingCloudApiReference.DngProperties();
      //expect(instance).to.be();
    });

    it('should have the property software (base name: "Software")', function() {
      // uncomment below and update the code to test the property software
      //var instance = new AsposeimagingCloudApiReference.DngProperties();
      //expect(instance).to.be();
    });

    it('should have the property rawCount (base name: "RawCount")', function() {
      // uncomment below and update the code to test the property rawCount
      //var instance = new AsposeimagingCloudApiReference.DngProperties();
      //expect(instance).to.be();
    });

    it('should have the property filters (base name: "Filters")', function() {
      // uncomment below and update the code to test the property filters
      //var instance = new AsposeimagingCloudApiReference.DngProperties();
      //expect(instance).to.be();
    });

    it('should have the property colorsCount (base name: "ColorsCount")', function() {
      // uncomment below and update the code to test the property colorsCount
      //var instance = new AsposeimagingCloudApiReference.DngProperties();
      //expect(instance).to.be();
    });

    it('should have the property xmpData (base name: "XmpData")', function() {
      // uncomment below and update the code to test the property xmpData
      //var instance = new AsposeimagingCloudApiReference.DngProperties();
      //expect(instance).to.be();
    });

    it('should have the property translationCfaDng (base name: "TranslationCfaDng")', function() {
      // uncomment below and update the code to test the property translationCfaDng
      //var instance = new AsposeimagingCloudApiReference.DngProperties();
      //expect(instance).to.be();
    });

  });

}));
