/**
 * Aspose.Imaging Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AsposeimagingCloudApiReference);
  }
}(this, function(expect, AsposeimagingCloudApiReference) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AsposeimagingCloudApiReference.JpegExifData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('JpegExifData', function() {
    it('should create an instance of JpegExifData', function() {
      // uncomment below and update the code to test JpegExifData
      //var instance = new AsposeimagingCloudApiReference.JpegExifData();
      //expect(instance).to.be.a(AsposeimagingCloudApiReference.JpegExifData);
    });

    it('should have the property artist (base name: "Artist")', function() {
      // uncomment below and update the code to test the property artist
      //var instance = new AsposeimagingCloudApiReference.JpegExifData();
      //expect(instance).to.be();
    });

    it('should have the property copyright (base name: "Copyright")', function() {
      // uncomment below and update the code to test the property copyright
      //var instance = new AsposeimagingCloudApiReference.JpegExifData();
      //expect(instance).to.be();
    });

    it('should have the property dateTime (base name: "DateTime")', function() {
      // uncomment below and update the code to test the property dateTime
      //var instance = new AsposeimagingCloudApiReference.JpegExifData();
      //expect(instance).to.be();
    });

    it('should have the property imageDescription (base name: "ImageDescription")', function() {
      // uncomment below and update the code to test the property imageDescription
      //var instance = new AsposeimagingCloudApiReference.JpegExifData();
      //expect(instance).to.be();
    });

    it('should have the property make (base name: "Make")', function() {
      // uncomment below and update the code to test the property make
      //var instance = new AsposeimagingCloudApiReference.JpegExifData();
      //expect(instance).to.be();
    });

    it('should have the property model (base name: "Model")', function() {
      // uncomment below and update the code to test the property model
      //var instance = new AsposeimagingCloudApiReference.JpegExifData();
      //expect(instance).to.be();
    });

    it('should have the property orientation (base name: "Orientation")', function() {
      // uncomment below and update the code to test the property orientation
      //var instance = new AsposeimagingCloudApiReference.JpegExifData();
      //expect(instance).to.be();
    });

    it('should have the property primaryChromaticities (base name: "PrimaryChromaticities")', function() {
      // uncomment below and update the code to test the property primaryChromaticities
      //var instance = new AsposeimagingCloudApiReference.JpegExifData();
      //expect(instance).to.be();
    });

    it('should have the property referenceBlackWhite (base name: "ReferenceBlackWhite")', function() {
      // uncomment below and update the code to test the property referenceBlackWhite
      //var instance = new AsposeimagingCloudApiReference.JpegExifData();
      //expect(instance).to.be();
    });

    it('should have the property resolutionUnit (base name: "ResolutionUnit")', function() {
      // uncomment below and update the code to test the property resolutionUnit
      //var instance = new AsposeimagingCloudApiReference.JpegExifData();
      //expect(instance).to.be();
    });

    it('should have the property software (base name: "Software")', function() {
      // uncomment below and update the code to test the property software
      //var instance = new AsposeimagingCloudApiReference.JpegExifData();
      //expect(instance).to.be();
    });

    it('should have the property transferFunction (base name: "TransferFunction")', function() {
      // uncomment below and update the code to test the property transferFunction
      //var instance = new AsposeimagingCloudApiReference.JpegExifData();
      //expect(instance).to.be();
    });

    it('should have the property xResolution (base name: "XResolution")', function() {
      // uncomment below and update the code to test the property xResolution
      //var instance = new AsposeimagingCloudApiReference.JpegExifData();
      //expect(instance).to.be();
    });

    it('should have the property yCbCrCoefficients (base name: "YCbCrCoefficients")', function() {
      // uncomment below and update the code to test the property yCbCrCoefficients
      //var instance = new AsposeimagingCloudApiReference.JpegExifData();
      //expect(instance).to.be();
    });

    it('should have the property yCbCrPositioning (base name: "YCbCrPositioning")', function() {
      // uncomment below and update the code to test the property yCbCrPositioning
      //var instance = new AsposeimagingCloudApiReference.JpegExifData();
      //expect(instance).to.be();
    });

    it('should have the property yResolution (base name: "YResolution")', function() {
      // uncomment below and update the code to test the property yResolution
      //var instance = new AsposeimagingCloudApiReference.JpegExifData();
      //expect(instance).to.be();
    });

  });

}));
