/**
 * Aspose.Imaging Cloud API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.AsposeimagingCloudApiReference);
  }
}(this, function(expect, AsposeimagingCloudApiReference) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new AsposeimagingCloudApiReference.OdgMetadata();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OdgMetadata', function() {
    it('should create an instance of OdgMetadata', function() {
      // uncomment below and update the code to test OdgMetadata
      //var instance = new AsposeimagingCloudApiReference.OdgMetadata();
      //expect(instance).to.be.a(AsposeimagingCloudApiReference.OdgMetadata);
    });

    it('should have the property generator (base name: "Generator")', function() {
      // uncomment below and update the code to test the property generator
      //var instance = new AsposeimagingCloudApiReference.OdgMetadata();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "Title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new AsposeimagingCloudApiReference.OdgMetadata();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "Description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new AsposeimagingCloudApiReference.OdgMetadata();
      //expect(instance).to.be();
    });

    it('should have the property subject (base name: "Subject")', function() {
      // uncomment below and update the code to test the property subject
      //var instance = new AsposeimagingCloudApiReference.OdgMetadata();
      //expect(instance).to.be();
    });

    it('should have the property keywords (base name: "Keywords")', function() {
      // uncomment below and update the code to test the property keywords
      //var instance = new AsposeimagingCloudApiReference.OdgMetadata();
      //expect(instance).to.be();
    });

    it('should have the property initialCreator (base name: "InitialCreator")', function() {
      // uncomment below and update the code to test the property initialCreator
      //var instance = new AsposeimagingCloudApiReference.OdgMetadata();
      //expect(instance).to.be();
    });

    it('should have the property creator (base name: "Creator")', function() {
      // uncomment below and update the code to test the property creator
      //var instance = new AsposeimagingCloudApiReference.OdgMetadata();
      //expect(instance).to.be();
    });

    it('should have the property printedBy (base name: "PrintedBy")', function() {
      // uncomment below and update the code to test the property printedBy
      //var instance = new AsposeimagingCloudApiReference.OdgMetadata();
      //expect(instance).to.be();
    });

    it('should have the property creationDateTime (base name: "CreationDateTime")', function() {
      // uncomment below and update the code to test the property creationDateTime
      //var instance = new AsposeimagingCloudApiReference.OdgMetadata();
      //expect(instance).to.be();
    });

    it('should have the property modificationDateTime (base name: "ModificationDateTime")', function() {
      // uncomment below and update the code to test the property modificationDateTime
      //var instance = new AsposeimagingCloudApiReference.OdgMetadata();
      //expect(instance).to.be();
    });

    it('should have the property printDateTime (base name: "PrintDateTime")', function() {
      // uncomment below and update the code to test the property printDateTime
      //var instance = new AsposeimagingCloudApiReference.OdgMetadata();
      //expect(instance).to.be();
    });

    it('should have the property documentTemplate (base name: "DocumentTemplate")', function() {
      // uncomment below and update the code to test the property documentTemplate
      //var instance = new AsposeimagingCloudApiReference.OdgMetadata();
      //expect(instance).to.be();
    });

    it('should have the property automaticReload (base name: "AutomaticReload")', function() {
      // uncomment below and update the code to test the property automaticReload
      //var instance = new AsposeimagingCloudApiReference.OdgMetadata();
      //expect(instance).to.be();
    });

    it('should have the property hyperlinkBehavior (base name: "HyperlinkBehavior")', function() {
      // uncomment below and update the code to test the property hyperlinkBehavior
      //var instance = new AsposeimagingCloudApiReference.OdgMetadata();
      //expect(instance).to.be();
    });

    it('should have the property language (base name: "Language")', function() {
      // uncomment below and update the code to test the property language
      //var instance = new AsposeimagingCloudApiReference.OdgMetadata();
      //expect(instance).to.be();
    });

    it('should have the property editingCycles (base name: "EditingCycles")', function() {
      // uncomment below and update the code to test the property editingCycles
      //var instance = new AsposeimagingCloudApiReference.OdgMetadata();
      //expect(instance).to.be();
    });

    it('should have the property editingDuration (base name: "EditingDuration")', function() {
      // uncomment below and update the code to test the property editingDuration
      //var instance = new AsposeimagingCloudApiReference.OdgMetadata();
      //expect(instance).to.be();
    });

    it('should have the property documentStatistics (base name: "DocumentStatistics")', function() {
      // uncomment below and update the code to test the property documentStatistics
      //var instance = new AsposeimagingCloudApiReference.OdgMetadata();
      //expect(instance).to.be();
    });

  });

}));
